- hosts: webservers

  tasks:
    - name: install git
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes
      tags: git
      become: yes

    - name: Update and upgrade apt packages
      become: yes
      apt:
        upgrade: yes
        update_cache: yes

    - name: Copy file gitconf
      ansible.builtin.template:
        src: "{{root_dir}}/templates/.gitconfig"
        dest: "/home/{{ item.name }}/.gitconfig"
      loop:
        "{{ users }}"
      tags: users
      become: yes